on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'print content ls Before action checkout'
        run: ls

      - uses: actions/checkout@v3 

      - name: 'print content ls After action checkout'
        run: ls  

